import Navbar from '@/components/Navbar';
import { Container } from '@mui/material';
import Head from 'next/head'

interface MainLayouProps {
  children: JSX.Element | JSX.Element[]
}

const MainLayout: React.FC<MainLayouProps> = ({children}) => {
  return ( 
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <Container style={{padding: '90px 0'}} maxWidth='md'>
        {children}
      </Container>
    </>
  );
}
 
export default MainLayout;